# Parameters are described by its name, value, and range.
# All three items separated by commas

# Default PARAMETERS

# ------------------------------Segment Parameters------------------------------
# Morphological element used for binary operations, e.g. opening, closing, etc.
element_size = 3
element_size_range = [3, 10]

# Connectivity used, use 4 or 8
connectivity = 4
connectivity_range = [4, 8]

# Marker size for watershed segmentation
Marker_size = 10
Marker_size_range = [2, 30]

# Images can be resampled to target width make processing faster
target_width = 1000
target_width_range = [500, 2000]

# Images can be resampled with factors to make processing faster
resample = 0.3
resample_range = [0.01, 1.0]

# Batch processing flag
do_batch = false

# Default threeway threshold for default method
high_thresh = 0.9
mid_thresh = 0.5
low_thresh = 0.2
default_range = [0.0, 1.0]

# Default setting values for iterative methods
max_thresh = 0.95
min_thresh = 0.05
step_size = 0.05

# Default setting values for high ppm method
threshold_value = 0.5
if_gaussianblur = "False"
ksize = 3

# Image resolution
px2mm = 1.0

# ------------------------------Default Input and Output Settings------------------------------
# Target image
raw_img_path = "."

# Background image
bknd_img_path = "None"

# Ruler image
ruler_img_path = "."

# Save path
save_path = " "

# Save path for Images
save_path_for_images = "."


# ------------------------------Filtering Parameters------------------------------
# Also ignore too small bubbles (equivalent diameter in mm)
min_size = 0.1
min_size_range = [0, 50]

max_size = 20000

# Reject abnormal bubbles from quantification. E>0.85 or S<0.9
max_eccentricity = 0.85
max_eccentricity_range = [0.1, 1.0]
min_solidity = 0.9
min_solidity_range = [0.1, 1.0]

# Parameters for find big and small bubbles
if_find_circles = "N"
L_maxA = 20.0
L_minA = 10.0
s_maxA = 5.0
s_minA = 1.0
